# fly.toml file generated for rebase-ipfs-proxy on 2022-03-31T16:02:54-07:00

app = "rebase-ipfs-proxy"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
