app = "rebase-ipfs"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image="ipfs/go-ipfs"

[mounts]
source="ipfs_data"
destination="/data/ipfs"

[env]
DATA="/data"
IPFS_PROFILE="server"

[[services]]
  internal_port = 4001
  protocol = "tcp"
  
  [[services.ports]]
    port = "4001"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
